name: Syntax check and format

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-node@v2
    - run: npm ci
    - name: linter
      run: npm run lint
    - name: prettier
      run: npm run format
    - name: commit
      uses: stefanzweifel/git-auto-commit-action@v4.1.2
      with:
        commit_message: Applied linting and formatting.
      
    
